language: golang

install:
  - go get github.com/google/uuid
  - go get github.com/golang/protobuf/proto
  - go get google.golang.org/grpc
  - go build path_gtfsrt.go
  - docker build . -t jamespfennell/path-train-gtfs-realtime:latest

deploy:
  - provider: script
    script: make docker-hub
    on:
      branch: master
