language: golang

script:
  - docker build . -t jamespfennell/path-train-gtfs-realtime:latest

after_success:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker tag jamespfennell/path-train-gtfs-realtime:latest jamespfennell/path-train-gtfs-realtime:build$TRAVIS_BUILD_NUMBER
  - docker push jamespfennell/path-train-gtfs-realtime:latest
  - docker push jamespfennell/path-train-gtfs-realtime:build$TRAVIS_BUILD_NUMBER
